### ISSUE TITLE
Add gifs / images to readme

### ISSUE THREAD

**Issue by ryantheleach** [dhleong/beholder#17]
Adding graphical examples of what the UI looks like, will get you more attention as people browse GitHub.

It needs to be in the readme, as that's the first thing people look at.

**Comment by dhleong** [comment]
I tried making a gif but it ended up being massive, so I recorded an [asciinema](https://asciinema.org/a/myE6rTzrYAKNUOM0ofDAguuxG) instead

**Comment by ryantheleach** [comment]
Thanks!

(Also holy hell that search is fast. Makes me wish I knew Go. to add some extensions)

**Comment by dhleong** [comment]
You're welcome! It took me a while to come around to go (there's still a lot of language features I miss, but they're supposedly coming in the next major version) but the backend team at my office uses it so this project was sort of to teach myself so I could help out there if needed. I was also inspired by [FZF](https://github.com/junegunn/fzf) which is just awesome.
